tag-name = "v{{version}}"
tag-message = "Release v{{version}}"
push = true
publish = false
consolidate-commits = true
sign-commit = false
sign-tag = false

pre-release-hook = ["sh", "-c", "cargo fmt -- --check && cargo clippy -- -D warnings && cargo test --locked"]