tag-name = "v{{version}}"
push = true
publish = true
consolidate-commits = true
sign-commit = false
sign-tag = false
allow-branch = ["main"]
pre-release-hook = ["sh", "-c", "cargo fmt -- --check && cargo xtask docs --check && cargo clippy -- -D warnings && cargo test --locked"]